name: GenAI
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - expat=2.7.3=h50f4ffc_4
  - libcxx=20.1.8=hd7fd590_1
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libmpdec=4.0.0=h80987f9_0
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - python=3.13.9=hc7d8306_100_cp313
  - python_abi=3.13=3_cp313
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py313hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py313hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.12.0
      - asyncpg==0.31.0
      - attrs==25.4.0
      - boto3==1.42.5
      - botocore==1.42.5
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - datasets==4.4.1
      - dill==0.4.0
      - distro==1.9.0
      - duckduckgo-search==8.1.1
      - faiss-cpu==1.13.1
      - filelock==3.20.0
      - fonttools==4.61.0
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - greenlet==3.3.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - jinja2==3.1.6
      - jiter==0.12.0
      - jmespath==1.0.1
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - kiwisolver==1.4.9
      - langchain-core==1.1.2
      - langchain-postgres==0.0.16
      - langsmith==0.4.56
      - lxml==6.0.2
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - networkx==3.6.1
      - numpy==2.3.5
      - openai==2.9.0
      - orjson==3.11.5
      - packaging==25.0
      - pandas==2.3.3
      - pgvector==0.3.6
      - pillow==12.0.0
      - primp==0.15.0
      - propcache==0.4.1
      - psycopg==3.3.2
      - psycopg-binary==3.3.2
      - psycopg-pool==3.3.0
      - pyarrow==22.0.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pymupdf==1.26.6
      - pyparsing==3.2.5
      - pypdfium2==5.1.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - s3transfer==0.16.0
      - safetensors==0.7.0
      - six==1.17.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.44
      - sympy==1.14.0
      - tabula-py==2.10.0
      - tenacity==9.1.2
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - torch==2.9.1
      - tqdm==4.67.1
      - transformers==4.57.3
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.6.1
      - uuid-utils==0.12.0
      - wordcloud==1.9.4
      - xxhash==3.6.0
      - yarl==1.22.0
      - zstandard==0.25.0
prefix: /Users/riaanmostert/opt/miniconda3/envs/GenAI
